//Script to check that the results of a search with "filetype:" in the query have the right extension

//Creation of a Chrome instance:
my_bro = Browser("Chrome")

//Navigation to google
my_bro.Goto("www.google.com")

//Find the query field
my_query = my_bro.SearchItem("lst-ib")

//Get the text to submit
text = "javascript tuto filetype: pdf"

//Assuming there is basic manipulation of strings available
filetype = strip(substring(text, findlast(text, "filetype:") ,text.length)))
filetype = uppercase(filetype)

//Submit a query
my_query.Submit(text)

//Get the list of results but only the part that display the type of file
results = my_bro.SearchTheItems("sFZIhb b w xsm")

//First check to see if all the results have an extension noted
check = (results.length == 10)

//Look into the results to see if the site is well in the host
if check then
  check = find_list(results,filetype)
end if

//Display of the result
if check then display("All results have the right file extension) else display("Some of the results have not the right file extension !")
