//Script to check that the results of a search with "filetype:" in the query have the right extension

//Creation of a Chrome instance:
my_bro = Browser("Chrome")

//Navigation to google
my_bro.Goto("www.google.com")

//Find the query field
my_query = my_bro.SearchItem("lst-ib")

//Get the text to submit
text = "inurl: gouv.fr"

//Assuming there is basic manipulation of strings available
content = strip(substring(text, findlast(text, "inurl:") ,text.length)))

//Submit a query
my_query.Submit(text)

//Get the list of results but only the part that display the type of file
results = my_bro.SearchTheItems("iUh30")

//Look into the results to see if the site is well in the host
check = find_list(results, content)

//Display of the result
if check then 
display("All results have " + content + " in their url")
else
display("Some results don't have " + content + " in their url")
